import { invoke } from '@tauri-apps/api/core';
import {
  SystemOverview,
  CleanCategory,
  CleanResult,
  CleanItem,
  LargeFileInfo,
  AppInfo,
  DeveloperProjectInfo,
  RamBoostResult,
} from '../types';

export const isTauriEnvironment = (): boolean => {
  return typeof window !== 'undefined' && '__TAURI_INTERNALS__' in window;
};

export async function fetchSystemOverview(): Promise<SystemOverview> {
  if (!isTauriEnvironment()) {
    // Mock for browser testing
    return {
      hostname: "MacBook-Pro.local",
      os_name: "macOS",
      os_version: "15.3 (Sequoia)",
      arch: "aarch64",
      cpu_brand: "Apple M3 Max",
      cpu_cores: 14,
      cpu_usage_percent: 18.4,
      total_memory_bytes: 36 * 1024 * 1024 * 1024,
      used_memory_bytes: 21 * 1024 * 1024 * 1024,
      free_memory_bytes: 15 * 1024 * 1024 * 1024,
      memory_usage_percent: 58.3,
      total_swap_bytes: 4 * 1024 * 1024 * 1024,
      used_swap_bytes: 512 * 1024 * 1024,
      uptime_seconds: 245000,
      disks: [
        {
          name: "Macintosh HD",
          mount_point: "/",
          total_bytes: 1000 * 1024 * 1024 * 1024,
          available_bytes: 342 * 1024 * 1024 * 1024,
          used_bytes: 658 * 1024 * 1024 * 1024,
          usage_percent: 65.8,
          file_system: "apfs",
          is_removable: false,
        }
      ],
      battery: {
        percentage: 92,
        state: "Charging",
        time_remaining: "0:45 to full",
      },
      trash_size_bytes: 2.4 * 1024 * 1024 * 1024,
      estimated_junk_bytes: 12.8 * 1024 * 1024 * 1024,
    };
  }

  return await invoke<SystemOverview>('get_system_overview');
}

export async function fetchSystemJunk(): Promise<CleanCategory[]> {
  if (!isTauriEnvironment()) {
    return [
      {
        id: "system_caches",
        name: "System & User Caches",
        description: "Temporary data buffers generated by running applications.",
        category_type: "system_caches",
        total_bytes: 4.8 * 1024 * 1024 * 1024,
        item_count: 34,
        safety_level: "safe",
        items: [
          {
            id: "1",
            path: "~/Library/Caches/Google/Chrome",
            name: "Chrome Web Cache",
            size_bytes: 1.8 * 1024 * 1024 * 1024,
            selected_by_default: true,
            category: "system_caches",
            description: "Temporary web browsing cache files",
            last_modified: Date.now() / 1000 - 86400,
            is_directory: true,
          },
          {
            id: "2",
            path: "~/Library/Caches/com.apple.Safari",
            name: "Safari Web Cache",
            size_bytes: 1.2 * 1024 * 1024 * 1024,
            selected_by_default: true,
            category: "system_caches",
            description: "Safari browser rendering cache",
            last_modified: Date.now() / 1000 - 120000,
            is_directory: true,
          }
        ]
      },
      {
        id: "developer_junk",
        name: "Developer Build Caches",
        description: "Xcode DerivedData, Gradle build folders, and npm caches.",
        category_type: "developer_junk",
        total_bytes: 8.4 * 1024 * 1024 * 1024,
        item_count: 8,
        safety_level: "safe",
        items: [
          {
            id: "3",
            path: "~/Library/Developer/Xcode/DerivedData",
            name: "Xcode DerivedData",
            size_bytes: 6.2 * 1024 * 1024 * 1024,
            selected_by_default: true,
            category: "developer_junk",
            description: "Intermediate Xcode compilation files",
            last_modified: Date.now() / 1000 - 43200,
            is_directory: true,
          }
        ]
      }
    ];
  }

  return await invoke<CleanCategory[]>('scan_all_junk');
}

export async function executeCleanItems(paths: string[]): Promise<CleanResult> {
  if (!isTauriEnvironment()) {
    return {
      success: true,
      freed_bytes: paths.length * 150 * 1024 * 1024,
      deleted_count: paths.length,
      failed_count: 0,
      errors: [],
    };
  }

  return await invoke<CleanResult>('clean_selected_items', { paths });
}

export async function fetchTrashBin(): Promise<CleanItem[]> {
  if (!isTauriEnvironment()) {
    return [
      {
        id: "t1",
        path: "~/.Trash/Old-Video-Export.mov",
        name: "Old-Video-Export.mov",
        size_bytes: 1.4 * 1024 * 1024 * 1024,
        selected_by_default: true,
        category: "trash",
        description: "Discarded video file in Trash",
        last_modified: Date.now() / 1000 - 300000,
        is_directory: false,
      },
      {
        id: "t2",
        path: "~/.Trash/ArchivedBackup.zip",
        name: "ArchivedBackup.zip",
        size_bytes: 850 * 1024 * 1024,
        selected_by_default: true,
        category: "trash",
        description: "Old backup archive in Trash",
        last_modified: Date.now() / 1000 - 500000,
        is_directory: false,
      }
    ];
  }

  return await invoke<CleanItem[]>('scan_trash_bin');
}

export async function executeEmptyTrash(): Promise<CleanResult> {
  if (!isTauriEnvironment()) {
    return {
      success: true,
      freed_bytes: 2.25 * 1024 * 1024 * 1024,
      deleted_count: 2,
      failed_count: 0,
      errors: [],
    };
  }

  return await invoke<CleanResult>('empty_trash_bin_cmd');
}

export async function fetchLargeFiles(minSizeMb: number = 25): Promise<LargeFileInfo[]> {
  if (!isTauriEnvironment()) {
    return [
      {
        path: "~/Downloads/macOS_Sonoma_Installer.dmg",
        name: "macOS_Sonoma_Installer.dmg",
        extension: "dmg",
        size_bytes: 12.8 * 1024 * 1024 * 1024,
        category: "installer",
        last_modified: Date.now() / 1000 - 86400 * 45,
        last_accessed: Date.now() / 1000 - 86400 * 40,
        age_days: 45,
      },
      {
        path: "~/Movies/Raw_4K_Footage.mp4",
        name: "Raw_4K_Footage.mp4",
        extension: "mp4",
        size_bytes: 4.2 * 1024 * 1024 * 1024,
        category: "video",
        last_modified: Date.now() / 1000 - 86400 * 120,
        last_accessed: Date.now() / 1000 - 86400 * 100,
        age_days: 120,
      }
    ];
  }

  return await invoke<LargeFileInfo[]>('scan_large_files_cmd', { minSizeMb });
}

export async function executeDeleteFiles(paths: string[]): Promise<CleanResult> {
  if (!isTauriEnvironment()) {
    return {
      success: true,
      freed_bytes: 5 * 1024 * 1024 * 1024,
      deleted_count: paths.length,
      failed_count: 0,
      errors: [],
    };
  }

  return await invoke<CleanResult>('delete_files', { paths });
}

export async function revealFileInFinder(path: string): Promise<void> {
  if (!isTauriEnvironment()) {
    console.log("Mock reveal in finder:", path);
    return;
  }
  await invoke('reveal_in_finder', { path });
}

export async function fetchInstalledApplications(): Promise<AppInfo[]> {
  if (!isTauriEnvironment()) {
    return [
      {
        id: "app-slack",
        name: "Slack",
        bundle_id: "com.tinyspeck.slackmacgap",
        version: "4.38.0",
        executable_path: "/Applications/Slack.app",
        icon_path: "",
        total_size_bytes: 2.1 * 1024 * 1024 * 1024,
        app_bundle_size_bytes: 350 * 1024 * 1024,
        data_size_bytes: 1.2 * 1024 * 1024 * 1024,
        cache_size_bytes: 550 * 1024 * 1024,
        preferences_size_bytes: 24 * 1024,
        leftover_paths: [
          {
            path: "~/Library/Application Support/Slack",
            item_type: "support",
            size_bytes: 1.2 * 1024 * 1024 * 1024,
            description: "Chat history & user preferences",
          },
          {
            path: "~/Library/Caches/com.tinyspeck.slackmacgap",
            item_type: "cache",
            size_bytes: 550 * 1024 * 1024,
            description: "Image & media caches",
          }
        ],
        is_system_app: false,
      }
    ];
  }

  return await invoke<AppInfo[]>('scan_applications');
}

export async function executeUninstallApp(executablePath: string, leftoverPaths: string[]): Promise<CleanResult> {
  if (!isTauriEnvironment()) {
    return {
      success: true,
      freed_bytes: 2.1 * 1024 * 1024 * 1024,
      deleted_count: leftoverPaths.length + 1,
      failed_count: 0,
      errors: [],
    };
  }

  return await invoke<CleanResult>('uninstall_application', { executablePath, leftoverPaths });
}

export async function executeResetApp(leftoverPaths: string[]): Promise<CleanResult> {
  if (!isTauriEnvironment()) {
    return {
      success: true,
      freed_bytes: 1.75 * 1024 * 1024 * 1024,
      deleted_count: leftoverPaths.length,
      failed_count: 0,
      errors: [],
    };
  }

  return await invoke<CleanResult>('reset_application', { leftoverPaths });
}

export async function fetchDeveloperProjects(): Promise<DeveloperProjectInfo[]> {
  if (!isTauriEnvironment()) {
    return [
      {
        id: "dp1",
        name: "Old-React-Landing-Page",
        project_path: "~/Documents/Projects/Old-React-Landing-Page",
        framework: "Node.js / Web",
        total_cleanable_bytes: 650 * 1024 * 1024,
        last_modified_days_ago: 95,
        cleanable_folders: [
          {
            path: "~/Documents/Projects/Old-React-Landing-Page/node_modules",
            folder_type: "node_modules",
            size_bytes: 650 * 1024 * 1024,
          }
        ]
      }
    ];
  }

  return await invoke<DeveloperProjectInfo[]>('scan_developer_space');
}

export async function executeCleanDeveloperFolders(folderPaths: string[]): Promise<CleanResult> {
  if (!isTauriEnvironment()) {
    return {
      success: true,
      freed_bytes: folderPaths.length * 400 * 1024 * 1024,
      deleted_count: folderPaths.length,
      failed_count: 0,
      errors: [],
    };
  }

  return await invoke<CleanResult>('clean_developer_projects', { folderPaths });
}

export async function executeOptimizeRam(): Promise<RamBoostResult> {
  if (!isTauriEnvironment()) {
    return {
      initial_free_bytes: 12 * 1024 * 1024 * 1024,
      final_free_bytes: 15.4 * 1024 * 1024 * 1024,
      freed_bytes: 3.4 * 1024 * 1024 * 1024,
      message: "Successfully flushed inactive RAM pages.",
    };
  }

  return await invoke<RamBoostResult>('optimize_ram');
}
